### ISSUE TITLE
Figure out webpack CSS

### ISSUE THREAD

**Issue by elainewlin** [elainewlin/MusicParsed#37]
Currently, we import css files into js bundles. There must be some better way in webpack.

**Comment by andersk** [comment]
This is supposed to be a thing you can do with html-webpack-plugin + file-loader + extract-loader, but it doesn’t work because extract-loader doesn’t support `@import` (peerigon/extract-loader#2).

You can use extract-text-webpack-plugin to generate CSS bundles (#38). This doesn’t save you from having to make JavaScript files just to import CSS. However, you can now include the CSS in the template separately from the JavaScript.

**Comment by andersk** [comment]
> This doesn’t save you from having to make JavaScript files just to import CSS.

Actually, see #40.
